apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkmk-pv
  namespace: checkmk
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - vers=3
    - nfsvers=3
    - local_lock=all
  nfs:
    path: /path/to/nfs/share/
    server: xxx.xxx.xxx.xxx
    vers: 3
####To resolve the "Bad file descriptor" problem, this deployment added a PersistentVolume configured to use NFS version 3 (instead of version 4). PersistentVolumeClaim has been adjusted to reference PersistentVolume directly, without using a StorageClass.
####The NFS server must support version 3 of the NFS protocol.
