apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-pv-claim
  namespace: checkmk
spec:
  storageClassName: ""
  volumeName: checkmk-pv
  resources:
    requests:
      storage: 16Gi
  accessModes:
    - ReadWriteOnce
